#dbUserPasswords:
#  dbuserPassword: ""

databases:
  mosip_mockidentitysystem:
    enabled: true
    host: "esignet-postgres-postgresql.esignet"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    branch: v0.10.0
