#dbUserPasswords:
#  dbuserPassword: ""

databases:
  mosip_mockidentitysystem:
    enabled: true
    host: "postgres-postgresql.postgres"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/esignet-mock-services.git
    branch: v0.9.3
