apiVersion: v2
name: mock-identity-system
description: A Helm chart for MOSIP mock-identity-system module
type: application
version: 0.10.1-SNAPSHOT
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - mock-identity-system
maintainers:
  - email: info@mosip.io
    name: MOSIP
