apiVersion: v2
name: mock-relying-party-service
description: A Helm chart to file server application.
type: application
version: 0.12.0
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - mock-relying-party-service
maintainers:
  - email: info@mosip.io
    name: MOSIP
