apiVersion: v2
name: mock-relying-party-ui
description: A Helm chart for MOSIP OIDC UI module
type: application
version: 0.12.0-develop
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - mock-relying-party-ui
maintainers:
  - email: info@mosip.io
    name: MOSIP
